### ISSUE TITLE
F7 Syntax check Error: Illegal argument: line must be non-negative

### ISSUE THREAD

**Issue by pokorsky** [hpcc-systems/vscode-ecl#109]
The syntax check stopped working after upgrading the extension to version 0.0.30.

On F7, I get a notification 'Error: Illegal argument: line must be non-negative'.

This is what I found in my console

```
[GordonSmith.ecl]Cannot read property 'document' of undefined
e.$onExtensionRuntimeError @ mainThreadExtensionService.ts:43
e._doInvokeHandler @ rpcProtocol.ts:265
e._invokeHandler @ rpcProtocol.ts:250
e._receiveRequest @ rpcProtocol.ts:196
e._receiveOneMessage @ rpcProtocol.ts:178
(anonymous) @ rpcProtocol.ts:111
(anonymous) @ rpcProtocol.ts:307
e.fire @ event.ts:140
(anonymous) @ ipc.net.ts:81
emitOne @ events.js:96
emit @ events.js:191
readableAddChunk @ _stream_readable.js:178
Readable.push @ _stream_readable.js:136
onread @ net.js:560
mainThreadExtensionService.ts:44 TypeError: Cannot read property 'document' of undefined
	at ECLDiagnostic.vscode.window.onDidChangeActiveTextEditor (C:\Users\pokorskyj\.vscode\extensions\GordonSmith.ecl-0.0.30\out\src\eclDiagnostic.js:16:49)
	at e.fire (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:89:496)
	at c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:688:563
	at e.fire (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:89:496)
	at e.$acceptDocumentsAndEditorsDelta (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:686:754)
	at e._doInvokeHandler (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:599:737)
	at e._invokeHandler (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:599:455)
	at e._receiveRequest (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:598:529)
	at e._receiveOneMessage (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:598:298)
	at c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:597:226
	at c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:600:324
	at c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:88:119
	at e.fire (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:89:496)
	at Socket.<anonymous> (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:145:1008)
	at emitOne (events.js:96:13)
	at Socket.emit (events.js:191:7)
	at readableAddChunk (_stream_readable.js:178:18)
	at Socket.Readable.push (_stream_readable.js:136:10)
	at Pipe.onread (net.js:560:20)
e.$onExtensionRuntimeError @ mainThreadExtensionService.ts:44
e._doInvokeHandler @ rpcProtocol.ts:265
e._invokeHandler @ rpcProtocol.ts:250
e._receiveRequest @ rpcProtocol.ts:196
e._receiveOneMessage @ rpcProtocol.ts:178
(anonymous) @ rpcProtocol.ts:111
(anonymous) @ rpcProtocol.ts:307
e.fire @ event.ts:140
(anonymous) @ ipc.net.ts:81
emitOne @ events.js:96
emit @ events.js:191
readableAddChunk @ _stream_readable.js:178
Readable.push @ _stream_readable.js:136
onread @ net.js:560
```

**Comment by GordonSmith** [comment]
Thanks for the stack trace – I am still unable to reproduce (and this was reported by 1 other user).  I suspect I should be able to add a guard based on the stack trace, but don’t know what the actual cause is...

**Comment by pokorsky** [comment]
I am on Win 7.
Yes, I have an open ECL file and press F7.
I can see the compiler output in OUTPUT/ECL but the PROBLEMS window is empty.

It helps to set `"ecl.eclccPath"` property in my user settings. No error notification occurs and the problems are listed as expected.

**Comment by GordonSmith** [comment]
@pokorsky I pushed 0.0.31 out with the guard, but suspect I may have just moved the issue.  Can you unset the eclccPath and retest?

**Comment by pokorsky** [comment]
Upgraded to 0.0.31. No matter if `ecl.eclccPath` is set or not I got the same error `Error: Error: Illegal argument: line must be non-negative`. This time no stack trace in the console.

**Comment by GordonSmith** [comment]
Hmmm - that is a bit worrying (and doesn't make sense yet to me).  
* What version of eclcc do you have installed (more than one?)?
* Where is it located?
* What version of HPCC Platform are you hitting (more than 1)?

**Comment by pokorsky** [comment]
versions: 5.4.6, 5.6.4, 6.0.2, 6.2.0, 6.4.2, 6.4.4, 6.4.6, 6.4.14
location: C:\Program Files (x86)\HPCCSystems
I have more than 1 platform. I configured several tasks to hit them. I have not changed the default `launch.json`. When I comment out `ecl.eclccPath` the extensions finds the latest version 6.4.14.
The compiler lists the errors correctly on F7 or file save in OUTPUT/ECL.
I have other user setting
```
    "ecl.includeFolders": [
        "C:\\Users\\...\\sources"
    ],
    // "ecl.eclccPath": "C:\\Program\\ Files\\ (x86)\\HPCCSystems\\6.4.2\\clienttools\\bin\\",
    // "ecl.eclccPath": "",
    "ecl.legacyMode": true,
    "ecl.syntaxArgs": [
        "-syntax"
    ],
```
My `launch.json`
```
  "configurations": [
    {
      "name": "localhost-hthor",
      "type": "ecl",
      "request": "launch",
      "mode": "submit",
      "workspace": "${workspaceRoot}",
      "program": "${file}",
      "protocol": "http",
      "serverAddress": "localhost",
      "port": 8010,
      "rejectUnauthorized": false,
      "targetCluster": "hthor",
      "eclccPath": "${config:ecl.eclccPath}",
      "eclccArgs": [],
      "includeFolders": "${config:ecl.includeFolders}",
      "legacyMode": "${config:ecl.legacyMode}",
      "resultLimit": 100,
      "user": "",
      "password": ""
    }
  ]
```

**Comment by gmarcan** [comment]
Hello. I updated to version 0.0.31 and I am still seeing this issue. The syntax check is not returning any valid results. Only "No problems have been detected", plus the message "Illegal argument: line must be non-negative" comes up.

**Comment by GordonSmith** [comment]
I have a hunch that a specific version of eclcc (maybe an old one) is being used to syntax check and is outputting a negative number for a line number (or my parsing code is pulling the wrong number from the message).

Which may be why specifying a specific version of eclcc is fixing it in some cases?

**Comment by gmarcan** [comment]
I updated my compiler to RC (LN Tools) 7.0.0, but the error still comes up. I am using legacy mode.

**Comment by GordonSmith** [comment]
I am adding some extra checks for valid line / column numbers on syntax check, which should hopefully help.

**Comment by pokorsky** [comment]
@GordonSmith, I removed all versions except 6.4.14 and restarted VSCode. No change.

After pressing F7 I can spot a node with the filename of the compiled ecl file and a sub-node "checking...". Then it gets replaced with "No problems have been detected".

Here you can see the anonymmised content from the OUTPUT/ECL tab 
```
[2018-05-31T14:25:48.647Z] WARNING clienttools/eclcc:  parseECLErrors:  Unable to parse "C:\Users\...myfile.ecl(412,16): error C2171: Object 'SELF' does not have a field named 'UnmappedP'"
[2018-05-31T14:25:48.647Z] WARNING clienttools/eclcc:  parseECLErrors:  Unable to parse "C:\Users\...myfile.ecl(412,16): error C2167: Unknown identifier "UnmappedP""
[2018-05-31T14:25:48.647Z] WARNING clienttools/eclcc:  parseECLErrors:  Unable to parse "C:\Users\...myfile.ecl(460,22): error C3002: syntax error near ":=" : expected ';'"
[2018-05-31T14:25:48.647Z] WARNING clienttools/eclcc:  parseECLErrors:  Unable to parse "C:\Users\...myfile.ecl(469,41): error C3002: syntax error near ":=" : expected ';'"
[2018-05-31T14:25:48.647Z] WARNING clienttools/eclcc:  parseECLErrors:  Unable to parse "C:\Users\...myfile.ecl(499,9): error C2111: Transform does not supply a value for field "SELF.unmappedp""
[2018-05-31T14:25:48.647Z] WARNING clienttools/eclcc:  parseECLErrors:  Unable to parse "C:\Users\...myfile.ecl(517,8): error C3001: Too many errors (max = 5); Aborting..."
[2018-05-31T14:25:48.647Z] WARNING debugger/ECLDEbugSession.ts:  syntaxCheck-warning:  c:\Users\...myotherfile.ecl C:\Users\...myfile.ecl(412,16): error C2171: Object 'SELF' does not have a field named 'UnmappedP',C:\Users\...myfile.ecl(412,16): error C2167: Unknown identifier "UnmappedP",C:\Users\...myfile.ecl(460,22): error C3002: syntax error near ":=" : expected ';',C:\Users\...myfile.ecl(469,41): error C3002: syntax error near ":=" : expected ';',C:\Users\...myfile.ecl(499,9): error C2111: Transform does not supply a value for field "SELF.unmappedp",C:\Users\...myfile.ecl(517,8): error C3001: Too many errors (max = 5); Aborting...
```

**Comment by GordonSmith** [comment]
Silly question are those "..." you anonymizing the content?  If not, then that is probably the issue (with my error parser).

**Comment by GordonSmith** [comment]
(Also https://github.com/hpcc-systems/vscode-ecl/pull/113 will probably move the error further down the food chain).

**Comment by pokorsky** [comment]
Good try ;-) Yes, "..." stands for anonymized parts. I wanted to show you the format of my output. If it is in the expected shape.

**Comment by GordonSmith** [comment]
FYI I pushed a new release - can you report back?

**Comment by pokorsky** [comment]
Upgrade to the version 0.0.34 helped. No error notification. Unfortunately, I do not see all the errors from the output in PROBLEMS.

I broke intentionally a dependent file. When I run the syntax check for the top level file I can see 2 nodes:
1. a file name of the top level file with a message that Object 'folder of dependency' does not have a field named 'broken file'
2. a node named '.' listing a message about overlapped paths

You can get a better picture from copied JSON for those 2 nodes
```json
{
  "resource": "/c:/Users/pokorskyj/Documents/GitSources/HPCC/DataPipeline/RunETL.ecl",
  "owner": "ecl",
  "code": "undefined",
  "severity": 8,
  "message": "2171:  Object 'Entities' does not have a field named 'BrokenEntity'",
  "startLineNumber": 16,
  "startColumn": 9,
  "endLineNumber": 16,
  "endColumn": 9
}
```
```json
{
  "resource": "/.",
  "owner": "ecl",
  "code": "undefined",
  "severity": 2,
  "message": "Include paths -I 'c:\\Users\\pokorskyj\\Documents\\GitSources' and 'C:\\Users\\pokorskyj\\Documents\\GitSources\\HPCC' overlap",
  "startLineNumber": 1,
  "startColumn": 1,
  "endLineNumber": 1,
  "endColumn": 1
}
```
I added the part `-I 'C:\\Users\\pokorskyj\\Documents\\GitSources\\HPCC' overlap"` in my settings as it is the ecl source root. It used to work this way before my upgrade to 0.0.30

**Comment by GordonSmith** [comment]
Version bumped - lets hope this is an end to it.

**Comment by pokorsky** [comment]
Yes. 0.0.35 works like a charm. Thank you very much.

Just eclccPath setting has no effect. It always use the newest version. Probably a different issue.

**Comment by gmarcan** [comment]
Confirmed. Issue seems to have been resolved in 0.0.35. Thank you for the quick turn around :)
